# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lena/Projects/delphinos-installer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lena/Projects/delphinos-installer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lena/Projects/delphinos-installer/CMakeFiles /home/lena/Projects/delphinos-installer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lena/Projects/delphinos-installer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named delphinos-installer

# Build rule for target.
delphinos-installer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 delphinos-installer
.PHONY : delphinos-installer

# fast build rule for target.
delphinos-installer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer.dir/build.make CMakeFiles/delphinos-installer.dir/build
.PHONY : delphinos-installer/fast

#=============================================================================
# Target rules for targets named delphinos-installer-elevated

# Build rule for target.
delphinos-installer-elevated: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 delphinos-installer-elevated
.PHONY : delphinos-installer-elevated

# fast build rule for target.
delphinos-installer-elevated/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/build
.PHONY : delphinos-installer-elevated/fast

#=============================================================================
# Target rules for targets named copy_system_files

# Build rule for target.
copy_system_files: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 copy_system_files
.PHONY : copy_system_files

# fast build rule for target.
copy_system_files/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copy_system_files.dir/build.make CMakeFiles/copy_system_files.dir/build
.PHONY : copy_system_files/fast

#=============================================================================
# Target rules for targets named copy_stylesheet

# Build rule for target.
copy_stylesheet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 copy_stylesheet
.PHONY : copy_stylesheet

# fast build rule for target.
copy_stylesheet/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copy_stylesheet.dir/build.make CMakeFiles/copy_stylesheet.dir/build
.PHONY : copy_stylesheet/fast

#=============================================================================
# Target rules for targets named delphinos-installer_autogen_timestamp_deps

# Build rule for target.
delphinos-installer_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 delphinos-installer_autogen_timestamp_deps
.PHONY : delphinos-installer_autogen_timestamp_deps

# fast build rule for target.
delphinos-installer_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer_autogen_timestamp_deps.dir/build.make CMakeFiles/delphinos-installer_autogen_timestamp_deps.dir/build
.PHONY : delphinos-installer_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named delphinos-installer_autogen

# Build rule for target.
delphinos-installer_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 delphinos-installer_autogen
.PHONY : delphinos-installer_autogen

# fast build rule for target.
delphinos-installer_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer_autogen.dir/build.make CMakeFiles/delphinos-installer_autogen.dir/build
.PHONY : delphinos-installer_autogen/fast

#=============================================================================
# Target rules for targets named delphinos-installer-elevated_autogen_timestamp_deps

# Build rule for target.
delphinos-installer-elevated_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 delphinos-installer-elevated_autogen_timestamp_deps
.PHONY : delphinos-installer-elevated_autogen_timestamp_deps

# fast build rule for target.
delphinos-installer-elevated_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated_autogen_timestamp_deps.dir/build.make CMakeFiles/delphinos-installer-elevated_autogen_timestamp_deps.dir/build
.PHONY : delphinos-installer-elevated_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named delphinos-installer-elevated_autogen

# Build rule for target.
delphinos-installer-elevated_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 delphinos-installer-elevated_autogen
.PHONY : delphinos-installer-elevated_autogen

# fast build rule for target.
delphinos-installer-elevated_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated_autogen.dir/build.make CMakeFiles/delphinos-installer-elevated_autogen.dir/build
.PHONY : delphinos-installer-elevated_autogen/fast

delphinos-installer-elevated_autogen/mocs_compilation.o: delphinos-installer-elevated_autogen/mocs_compilation.cpp.o
.PHONY : delphinos-installer-elevated_autogen/mocs_compilation.o

# target to build an object file
delphinos-installer-elevated_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/delphinos-installer-elevated_autogen/mocs_compilation.cpp.o
.PHONY : delphinos-installer-elevated_autogen/mocs_compilation.cpp.o

delphinos-installer-elevated_autogen/mocs_compilation.i: delphinos-installer-elevated_autogen/mocs_compilation.cpp.i
.PHONY : delphinos-installer-elevated_autogen/mocs_compilation.i

# target to preprocess a source file
delphinos-installer-elevated_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/delphinos-installer-elevated_autogen/mocs_compilation.cpp.i
.PHONY : delphinos-installer-elevated_autogen/mocs_compilation.cpp.i

delphinos-installer-elevated_autogen/mocs_compilation.s: delphinos-installer-elevated_autogen/mocs_compilation.cpp.s
.PHONY : delphinos-installer-elevated_autogen/mocs_compilation.s

# target to generate assembly for a file
delphinos-installer-elevated_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/delphinos-installer-elevated_autogen/mocs_compilation.cpp.s
.PHONY : delphinos-installer-elevated_autogen/mocs_compilation.cpp.s

delphinos-installer_autogen/mocs_compilation.o: delphinos-installer_autogen/mocs_compilation.cpp.o
.PHONY : delphinos-installer_autogen/mocs_compilation.o

# target to build an object file
delphinos-installer_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer.dir/build.make CMakeFiles/delphinos-installer.dir/delphinos-installer_autogen/mocs_compilation.cpp.o
.PHONY : delphinos-installer_autogen/mocs_compilation.cpp.o

delphinos-installer_autogen/mocs_compilation.i: delphinos-installer_autogen/mocs_compilation.cpp.i
.PHONY : delphinos-installer_autogen/mocs_compilation.i

# target to preprocess a source file
delphinos-installer_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer.dir/build.make CMakeFiles/delphinos-installer.dir/delphinos-installer_autogen/mocs_compilation.cpp.i
.PHONY : delphinos-installer_autogen/mocs_compilation.cpp.i

delphinos-installer_autogen/mocs_compilation.s: delphinos-installer_autogen/mocs_compilation.cpp.s
.PHONY : delphinos-installer_autogen/mocs_compilation.s

# target to generate assembly for a file
delphinos-installer_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer.dir/build.make CMakeFiles/delphinos-installer.dir/delphinos-installer_autogen/mocs_compilation.cpp.s
.PHONY : delphinos-installer_autogen/mocs_compilation.cpp.s

delphinosInstallerElevated.o: delphinosInstallerElevated.cpp.o
.PHONY : delphinosInstallerElevated.o

# target to build an object file
delphinosInstallerElevated.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/delphinosInstallerElevated.cpp.o
.PHONY : delphinosInstallerElevated.cpp.o

delphinosInstallerElevated.i: delphinosInstallerElevated.cpp.i
.PHONY : delphinosInstallerElevated.i

# target to preprocess a source file
delphinosInstallerElevated.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/delphinosInstallerElevated.cpp.i
.PHONY : delphinosInstallerElevated.cpp.i

delphinosInstallerElevated.s: delphinosInstallerElevated.cpp.s
.PHONY : delphinosInstallerElevated.s

# target to generate assembly for a file
delphinosInstallerElevated.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/delphinosInstallerElevated.cpp.s
.PHONY : delphinosInstallerElevated.cpp.s

installationPage.o: installationPage.cpp.o
.PHONY : installationPage.o

# target to build an object file
installationPage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/installationPage.cpp.o
.PHONY : installationPage.cpp.o

installationPage.i: installationPage.cpp.i
.PHONY : installationPage.i

# target to preprocess a source file
installationPage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/installationPage.cpp.i
.PHONY : installationPage.cpp.i

installationPage.s: installationPage.cpp.s
.PHONY : installationPage.s

# target to generate assembly for a file
installationPage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/installationPage.cpp.s
.PHONY : installationPage.cpp.s

localizationPage.o: localizationPage.cpp.o
.PHONY : localizationPage.o

# target to build an object file
localizationPage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/localizationPage.cpp.o
.PHONY : localizationPage.cpp.o

localizationPage.i: localizationPage.cpp.i
.PHONY : localizationPage.i

# target to preprocess a source file
localizationPage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/localizationPage.cpp.i
.PHONY : localizationPage.cpp.i

localizationPage.s: localizationPage.cpp.s
.PHONY : localizationPage.s

# target to generate assembly for a file
localizationPage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/localizationPage.cpp.s
.PHONY : localizationPage.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer.dir/build.make CMakeFiles/delphinos-installer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer.dir/build.make CMakeFiles/delphinos-installer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer.dir/build.make CMakeFiles/delphinos-installer.dir/main.cpp.s
.PHONY : main.cpp.s

mainWindow.o: mainWindow.cpp.o
.PHONY : mainWindow.o

# target to build an object file
mainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/mainWindow.cpp.o
.PHONY : mainWindow.cpp.o

mainWindow.i: mainWindow.cpp.i
.PHONY : mainWindow.i

# target to preprocess a source file
mainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/mainWindow.cpp.i
.PHONY : mainWindow.cpp.i

mainWindow.s: mainWindow.cpp.s
.PHONY : mainWindow.s

# target to generate assembly for a file
mainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/mainWindow.cpp.s
.PHONY : mainWindow.cpp.s

networkDBus.o: networkDBus.cpp.o
.PHONY : networkDBus.o

# target to build an object file
networkDBus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/networkDBus.cpp.o
.PHONY : networkDBus.cpp.o

networkDBus.i: networkDBus.cpp.i
.PHONY : networkDBus.i

# target to preprocess a source file
networkDBus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/networkDBus.cpp.i
.PHONY : networkDBus.cpp.i

networkDBus.s: networkDBus.cpp.s
.PHONY : networkDBus.s

# target to generate assembly for a file
networkDBus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/networkDBus.cpp.s
.PHONY : networkDBus.cpp.s

networkPage.o: networkPage.cpp.o
.PHONY : networkPage.o

# target to build an object file
networkPage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/networkPage.cpp.o
.PHONY : networkPage.cpp.o

networkPage.i: networkPage.cpp.i
.PHONY : networkPage.i

# target to preprocess a source file
networkPage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/networkPage.cpp.i
.PHONY : networkPage.cpp.i

networkPage.s: networkPage.cpp.s
.PHONY : networkPage.s

# target to generate assembly for a file
networkPage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/networkPage.cpp.s
.PHONY : networkPage.cpp.s

partitionPage.o: partitionPage.cpp.o
.PHONY : partitionPage.o

# target to build an object file
partitionPage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/partitionPage.cpp.o
.PHONY : partitionPage.cpp.o

partitionPage.i: partitionPage.cpp.i
.PHONY : partitionPage.i

# target to preprocess a source file
partitionPage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/partitionPage.cpp.i
.PHONY : partitionPage.cpp.i

partitionPage.s: partitionPage.cpp.s
.PHONY : partitionPage.s

# target to generate assembly for a file
partitionPage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/partitionPage.cpp.s
.PHONY : partitionPage.cpp.s

usersPage.o: usersPage.cpp.o
.PHONY : usersPage.o

# target to build an object file
usersPage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/usersPage.cpp.o
.PHONY : usersPage.cpp.o

usersPage.i: usersPage.cpp.i
.PHONY : usersPage.i

# target to preprocess a source file
usersPage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/usersPage.cpp.i
.PHONY : usersPage.cpp.i

usersPage.s: usersPage.cpp.s
.PHONY : usersPage.s

# target to generate assembly for a file
usersPage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/delphinos-installer-elevated.dir/build.make CMakeFiles/delphinos-installer-elevated.dir/usersPage.cpp.s
.PHONY : usersPage.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... copy_stylesheet"
	@echo "... copy_system_files"
	@echo "... delphinos-installer-elevated_autogen"
	@echo "... delphinos-installer-elevated_autogen_timestamp_deps"
	@echo "... delphinos-installer_autogen"
	@echo "... delphinos-installer_autogen_timestamp_deps"
	@echo "... delphinos-installer"
	@echo "... delphinos-installer-elevated"
	@echo "... delphinos-installer-elevated_autogen/mocs_compilation.o"
	@echo "... delphinos-installer-elevated_autogen/mocs_compilation.i"
	@echo "... delphinos-installer-elevated_autogen/mocs_compilation.s"
	@echo "... delphinos-installer_autogen/mocs_compilation.o"
	@echo "... delphinos-installer_autogen/mocs_compilation.i"
	@echo "... delphinos-installer_autogen/mocs_compilation.s"
	@echo "... delphinosInstallerElevated.o"
	@echo "... delphinosInstallerElevated.i"
	@echo "... delphinosInstallerElevated.s"
	@echo "... installationPage.o"
	@echo "... installationPage.i"
	@echo "... installationPage.s"
	@echo "... localizationPage.o"
	@echo "... localizationPage.i"
	@echo "... localizationPage.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainWindow.o"
	@echo "... mainWindow.i"
	@echo "... mainWindow.s"
	@echo "... networkDBus.o"
	@echo "... networkDBus.i"
	@echo "... networkDBus.s"
	@echo "... networkPage.o"
	@echo "... networkPage.i"
	@echo "... networkPage.s"
	@echo "... partitionPage.o"
	@echo "... partitionPage.i"
	@echo "... partitionPage.s"
	@echo "... usersPage.o"
	@echo "... usersPage.i"
	@echo "... usersPage.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

