#include <QMap>

QMap<int, QString> networkTypeMap
{
    { 1, "Ethernet" },
    { 2, "Wi-Fi" },
    { 3, "Bridge" },
    { 4, "Loopback" },
    { 5, "Tunnel" },
    { 6, "VLAN" },
    { 7, "ADSL" },
    { 8, "MACVLAN" },
    { 10, "Bond" },
    { 11, "Team" },
    { 12, "IP Tunnel" },
    { 13, "Virtual Bridge" },
    { 14, "MACsec" },
    { 15, "Virtual Ethernet" },
    { 16, "Virtual Network" },
    { 17, "Point-to-Point Prococol" },
    { 18, "OVS Bridge" },
    { 19, "OVS Port" },
    { 20, "OVS Interface" },
    { 21, "Generic" },
    { 22, "TUN" },
    { 23, "TAP" },
    { 24, "IP6 Tunnel" },
    { 25, "WireGuard" },
    { 26, "Wi-Fi Point-to-Point" },
    { 27, "VRF" },
    { 28, "Lowpan" },
    { 29, "Dummy" },
    { 30, "Point-to-Point Prococol over Ethernet" },
    { 31, "InfiniBand" },
    { 32, "Loopback" },
};